#
# This config exists as a demonstration of generating an alert with particular
# labels and sending to an alertmanager.
#
# We add env:local-dev as an external_label to make clear what's going
# on in the alertmanager
#
# Just run `prometheus` without any arguments from this directory.
global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    env: phils-laptop

rule_files:
  - 'rules/*'

alerting:
  alertmanagers:
  # Here is an example configuration for sending to a specific alertmanager:
  # it is commented out by default to avoid annoying the support person
  - scheme: https
    tls_config:
      server_name: alerts.monitoring-staging.gds-reliability.engineering
    dns_sd_configs:
    - names: [ alerts.monitoring-staging.gds-reliability.engineering ]
      type: A
      port: 443

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
