groups:
- name: AlertManager
  rules:
  - alert: AlertManager_Below_Threshold
    expr: up{job="alertmanager"} == 0 and on(job) sum by(job) (up{job="alertmanager"}) <= 1
    for: 10s
    labels:
        severity: "P2"
        product: "tools"
    annotations:
        summary: "Service is below the expected instance Threshold"
        description: "The service name is {{ $labels.job }}. The URL experiencing the issue is {{ $labels.instance }}"

# this can be improved however maybe this is something we need to focus on in Q2 when working on the support plan
