groups:
- name: DataGovUk
  rules:
  - alert: DataGovUk_HighCpuUsage
    expr: avg(cpu{job="metric-exporter"}) by (app) >= 80
    for: 5m
    labels:
        product: "data-gov-uk"
    annotations:
        summary: "App {{ $labels.app }} has high CPU usage"
        description: "Application {{ $labels.app }} has been using over 80% CPU (averaged over all instances) for 5 minutes or more."
  - alert: DataGovUk_HighDiskUsage
    expr: max(disk_utilization{job="metric-exporter"}) by (app) >= 80
    labels:
        product: "data-gov-uk"
    annotations:
        summary: "App {{ $labels.app }} has high disk usage"
        description: "Application {{ $labels.app }} has an instance which is using over 80% disk."
  - alert: DataGovUk_ElasticSearchIndexSizeIncrease
    expr: max by (job) (delta(elasticsearch_indices_docs{space="data-gov-uk"}[30m])) >= 100
    for: 1m
    labels:
        product: "data-gov-uk"
    annotations:
        summary: "Index size of Elasticsearch for {{ $labels.job }} has increased significantly"
        description: "The index size of Elasticsearch for {{ $labels.job }} has increased by more than 100 documents in the last 30 minutes"
  - alert: DataGovUk_ElasticSearchIndexSizeDecrease
    expr: max by (job) (delta(elasticsearch_indices_docs{space="data-gov-uk"}[30m])) <= -100
    for: 1m
    labels:
        product: "data-gov-uk"
    annotations:
        summary: "Index size of Elasticsearch for {{ $labels.job }} has decreased significantly"
        description: "The index size of Elasticsearch for {{ $labels.job }} has decreased by more than 100 documents in the last 30 minutes"
