groups:
- name: Registers
  rules:
  - alert: RequestsExcess5xx
    expr: sum by(app) (rate(requests{job="openregister-metric-exporter", exported_space="prod", status_range="5xx"}[5m])) / sum by(app) (rate(requests{job="openregister-metric-exporter", exported_space="prod"}[5m])) >= 0.25
    for: 120s
    labels:
        product: "registers"
    annotations:
        summary: "App {{ $labels.app }} has too many 5xx errors"
        description: "App {{ $labels.app }} has 5xx errors in excess of 25% of total requests"
