groups:
- name: VerifyAlerts
  rules:
  - alert: Verify_Filesystem_Filling_Up
    # we explicitly exclude tmpfs filesystems because they don't correspond to a disk
    # filling up
    expr: predict_linear(node_filesystem_avail_bytes{fstype!="tmpfs"}[1h], 86400) < 0
    for: 10s
    labels:
        product: "prometheus"
        severity: "ticket"
    annotations:
        summary: "Filesystem {{ $labels.mountpoint }} on {{ $labels.instance }} predicted to fill up within 24 hours"
        description: "Based on the trend over the past hour, it looks like {{ $labels.mountpoint }} on {{ $labels.instance }} will fill up within the next 24 hours."
        runbook: "https://github.com/alphagov/verify-puppet/wiki/Increase-disk-space-on-boxes"
