#
# This config exists as a way of generating an alert from verify's prometheus
# for a user research session.
#
# It works like this:
#
#   - scrape the verify prometheus's federate endpoint to get their metrics locally
#   - evaluate alerts locally based on verify metrics
#   - send alerts directly to production alertmanager
#
# This is certainly a hack but it is all we need for a user research scenario

global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    env: local-dev
alerting:
  alertmanagers:
  - scheme: https
    static_configs:
      - targets: ["alerts-1.monitoring.gds-reliability.engineering"]
rule_files:
  - "./alerts/*"
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: verify_federate
    scheme: https
    honor_labels: true
    metrics_path: '/federate'
    basic_auth:
      username: ida
      # note that the password file is .gitignore'd
      password_file: ./ida-password
    params:
      'match[]':
        - '{__name__=~"..*"}'
    static_configs:
      - targets: ["prometheus-hub-perf-a-dmz.ida.digital.cabinet-office.gov.uk"]
