driver:
  name: terraform

provisioner:
  name: terraform

platforms:
  - name: west1
    driver:
      root_module_directory: test/prometheus-paas

suites:
  - name: paas
    lifecycle:
      post_converge:
      - local: echo 'Post converge- sleep 120 seconds'; sleep 120
    verifier:
      name: terraform
      systems:
      - name: aws_cloud
        backend: aws
        controls:
          - aws_cloud_resources

      - name: os_checks
        backend: ssh
        sudo: true
        hosts_output: prometheus_dns
        controls:
          - operating_system
        user: <%= ENV['SSH_USER'] || "ubuntu" %>
    excludes:
      - west2
